[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 manage.py collectstatic --noinput && python3 manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
